### ISSUE TITLE
Thorough checklist of tests for TypeChecker

### ISSUE THREAD

**Issue by elben** [elben/neblen#2]
- [ ] Go through existing tests and verify correctness of environments and output
- [ ] Write thorough tests for each check function.
- [ ] Tests for deeply-nested things with confusing closures, to make sure TEnv and UEnv are thrown away and kept as appropriate.
